// constants/landingProductConstants.js

export const LANDING_PRODUCT_LIST_REQUEST = 'LANDING_PRODUCT_LIST_REQUEST';
export const LANDING_PRODUCT_LIST_SUCCESS = 'LANDING_PRODUCT_LIST_SUCCESS';
export const LANDING_PRODUCT_LIST_FAIL    = 'LANDING_PRODUCT_LIST_FAIL';

export const LANDING_PRODUCT_DETAILS_REQUEST = 'LANDING_PRODUCT_DETAILS_REQUEST';
export const LANDING_PRODUCT_DETAILS_SUCCESS = 'LANDING_PRODUCT_DETAILS_SUCCESS';
export const LANDING_PRODUCT_DETAILS_FAIL    = 'LANDING_PRODUCT_DETAILS_FAIL';

export const LANDING_PRODUCT_CREATE_REQUEST = 'LANDING_PRODUCT_CREATE_REQUEST';
export const LANDING_PRODUCT_CREATE_SUCCESS = 'LANDING_PRODUCT_CREATE_SUCCESS';
export const LANDING_PRODUCT_CREATE_FAIL    = 'LANDING_PRODUCT_CREATE_FAIL';
export const LANDING_PRODUCT_CREATE_RESET   = 'LANDING_PRODUCT_CREATE_RESET';

export const LANDING_PRODUCT_UPDATE_REQUEST = 'LANDING_PRODUCT_UPDATE_REQUEST';
export const LANDING_PRODUCT_UPDATE_SUCCESS = 'LANDING_PRODUCT_UPDATE_SUCCESS';
export const LANDING_PRODUCT_UPDATE_FAIL    = 'LANDING_PRODUCT_UPDATE_FAIL';
export const LANDING_PRODUCT_UPDATE_RESET   = 'LANDING_PRODUCT_UPDATE_RESET';

export const LANDING_PRODUCT_DELETE_REQUEST = 'LANDING_PRODUCT_DELETE_REQUEST';
export const LANDING_PRODUCT_DELETE_SUCCESS = 'LANDING_PRODUCT_DELETE_SUCCESS';
export const LANDING_PRODUCT_DELETE_FAIL    = 'LANDING_PRODUCT_DELETE_FAIL';

export const LANDING_PRODUCT_CREATE_REVIEW_REQUEST = 'LANDING_PRODUCT_CREATE_REVIEW_REQUEST';
export const LANDING_PRODUCT_CREATE_REVIEW_SUCCESS = 'LANDING_PRODUCT_CREATE_REVIEW_SUCCESS';
export const LANDING_PRODUCT_CREATE_REVIEW_FAIL    = 'LANDING_PRODUCT_CREATE_REVIEW_FAIL';
export const LANDING_PRODUCT_CREATE_REVIEW_RESET   = 'LANDING_PRODUCT_CREATE_REVIEW_RESET';